# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "buildAndTestLinux"
  buildAndTestLinux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
          projectPath:
            - test-project
          unityVersion:
                - 2019.4.12f1
          targetPlatform:
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - StandaloneLinux64 # Build a Linux 64-bit standalone.
          - Android # Build an Android player.
            
            
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          lfs: true
        
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: Library
          key: Library
      - name: Unity - Test runner
        uses: game-ci/unity-test-runner@v2.0-alpha-5

      # Runs a single command using the runners shell
      - name: Unity - Builder
        uses: game-ci/unity-builder@v2.0-alpha-8

